test: refactor test code because of static global Sandbox will panic when cargo test
- When use lazy_static to make near Sandbox static and global, it'll
  panicked at 'dispatch dropped without returning error' when execute
  `cargo test`.